// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7cSHj5H6SliG7brFo0BKe-A1b59X1jkM',
    appId: '1:550163998966:web:037a968be53580206ae4d7',
    messagingSenderId: '550163998966',
    projectId: 'update-needpedia',
    authDomain: 'update-needpedia.firebaseapp.com',
    storageBucket: 'update-needpedia.appspot.com',
    measurementId: 'G-76CH3Y8WS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaPu3h5N-fYPn3R0iJhEF4v60UTSBFrBE',
    appId: '1:550163998966:android:5ce9e730dc732e066ae4d7',
    messagingSenderId: '550163998966',
    projectId: 'update-needpedia',
    storageBucket: 'update-needpedia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgKnvlW7NfsrrddHhMmAuEWHPvdMOsSgc',
    appId: '1:550163998966:ios:c3de314d3983f6496ae4d7',
    messagingSenderId: '550163998966',
    projectId: 'update-needpedia',
    storageBucket: 'update-needpedia.appspot.com',
    iosBundleId: 'com.example.needpedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgKnvlW7NfsrrddHhMmAuEWHPvdMOsSgc',
    appId: '1:550163998966:ios:c3de314d3983f6496ae4d7',
    messagingSenderId: '550163998966',
    projectId: 'update-needpedia',
    storageBucket: 'update-needpedia.appspot.com',
    iosBundleId: 'com.example.needpedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7cSHj5H6SliG7brFo0BKe-A1b59X1jkM',
    appId: '1:550163998966:web:68c632f7ff339c146ae4d7',
    messagingSenderId: '550163998966',
    projectId: 'update-needpedia',
    authDomain: 'update-needpedia.firebaseapp.com',
    storageBucket: 'update-needpedia.appspot.com',
    measurementId: 'G-54J0V038R5',
  );
}
